---
name: 'Sumneko Lint'
decription: 'Type check and lint lua code using lua-language-server.'
inputs:
  checklevel:
    description: "The diagnostics severity level to fail on."
    required: true
    default: Warning
    type: choice
    options:
      - Error
      - Warning
      - Information
      - Hint
  directories:
    description: "The directories to lint (relative to the repository root)."
    required: true
    default: |
      lua
    type: string
  configpath:
    description: "Path to a luarc.json config file."
    required: false
    type: string
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.checklevel }}
    - ${{ inputs.directories }}
    - ${{ inputs.configpath }}
